name: Build Manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'vim tagname to build (example: v7.2; leave empty for latest)'
        required: false
      reason:
        description: 'why building this version manually (shown in release note)'
        required: true

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Generate artifacts
      run: sh package.sh

    - name: Set version
      id: latest-ver-get
      run: printf '::set-output name=latest::%s\n' ${{ github.event.inputs.version }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.latest-ver-get.outputs.latest }}
        release_name: Package ${{ steps.latest-ver-get.outputs.latest }}
        draft: false
        prerelease: true
        body: ${{ github.event.inputs.reason }}

    - name: Upload Release Asset i686
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./i686.7z
        asset_name: ${{ steps.latest-ver-get.outputs.latest }}-i686.7z
        asset_content_type: application/x-7z-compressed

    - name: Upload Release Asset x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./x86_64.7z
        asset_name: ${{ steps.latest-ver-get.outputs.latest }}-x86_64.7z
        asset_content_type: application/x-7z-compressed
